### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 

spring.jmx:
   enabled: false

callcenter:
    numThreads:   10
    minCallTime:   5
    maxCallTime:  10 

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

project:
  name: almundo-callcenter
  version: 0.1
  description: almundo-callcenter default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

---
spring:
  profiles: test
  
almundo.callcenter:
  name: 'test profile:'
  
logging:
  file: almundo.log
  


 